### ISSUE TITLE
Minor Issues for diskutil: APFS missing verb 'defragment', appleRAID completion broken (and missing verb 'list')

### ISSUE THREAD

**Issue by mascguy** [Honestpuck/apple_complete#2]
Fixes completed and committed to my local repository.

If you can create a branch for me, I'll push my changes and create a Pull Request.

And finally, thank you for publishing this work... it's exactly what I've been looking for! I'll contribute more, as I become more proficient in BASH completion authoring.

**Comment by mascguy** [comment]
Pull request created:

[Improvements and fixes, for verbs APFS and appleRAID](https://github.com/Honestpuck/apple_complete/pull/3)

**Comment by Honestpuck** [comment]
Thanks for that work, highly appreciated.

ATM I'm contemplating having a look at the requirements for zsh completion since we should all be using zsh :😃

**Comment by mascguy** [comment]
No problem, sorry it took so long to submit the pull request. And thanks again for sharing these completions with the community, they've been a lifesaver!
